apiVersion: flightctl.io/v1alpha1
kind: Fleet
metadata:
 name: fleet-acm
spec:
 selector:
  matchLabels:
   fleet: acm
 template:
  spec:
    os:
      image: BOOTC_IMAGE
    config:
      - name: acm-crd
        httpRef:
          filePath: /var/local/acm-import/crd.yaml
          repository: acm-registration
          suffix: /agent-registration/crds/v1
      - name: acm-import
        httpRef:
          filePath: /var/local/acm-import/import.yaml
          repository: acm-registration
          suffix: /agent-registration/manifests/{{.metadata.name}}
      - name: apply-acm-manifests
        inline:
          - path: "/etc/flightctl/hooks.d/afterupdating/50-acm-registration.yaml"
            content: |
              - if:
                - path: /var/local/acm-import/crd.yaml
                  op: [created]
                run: kubectl apply -f /var/local/acm-import/crd.yaml
                envVars:
                  KUBECONFIG: /var/lib/microshift/resources/kubeadmin/kubeconfig
              - if:
                - path: /var/local/acm-import/import.yaml
                  op: [created]
                run: kubectl apply -f /var/local/acm-import/import.yaml
                envVars:
                  KUBECONFIG: /var/lib/microshift/resources/kubeadmin/kubeconfig
