apiVersion: v1
kind: Service
metadata:
  name: windguard-demo-vm-http
spec:
  selector:
    ocpvirt.io/vm: windguard-demo-vm-ocpvirt
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: windguard-demo-vm-https
spec:
  selector:
    ocpvirt.io/vm: windguard-demo-vm-ocpvirt
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
