---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    ocpvirt.io/vm: windguard-demo
  name: windguard-demo-vm
  namespace: windguard-demo
spec:
  dataVolumeTemplates:
  - metadata:
      name: windguard-demo-vm-dv
    spec:
      pvc:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 50Gi
      source:
        registry:
          url: docker://QCOW_IMAGE
  running: true
  template:
    metadata:
      labels:
        ocpvirt.io/vm: windguard-demo-vm-ocpvirt
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: datavolumedisk1
        resources:
          requests:
            memory: 4Gi
        firmware:
          bootloader:
            efi:
              secureBoot: false
        cpu:
          cores: 4
      terminationGracePeriodSeconds: 0
      volumes:
      - dataVolume:
          name: windguard-demo-vm-dv
        name: datavolumedisk1
