apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: windguard-demo-setup
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: demo-environment-setup/ocp-resources/ocp-setup/gitops
    repoURL: https://github.com/kubealex/windguard.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    retry:
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 1m
      limit: 5
